upgrade to Symfony 6.3
kollex/BehatMessengerContext pull request #9
Opened 2023-07-26 08:48 UTC by hbagherzadegan

### please **don't merge this** until all service ready for symfony 6.3

2023-11-15 13:24 UTC, hbagherzadegan commented
we have some specific methods which use in behat-context package which is not exist in macpaw/behat-messenger-context , to remove this package we should adjust and remove using that method in all package which use BehatMessengerContext check this : https://kollex.atlassian.net/browse/DEV-4047

2023-11-16 15:33 UTC, JarJak requested changes

2023-11-16 15:33 UTC, JarJak commented on .github/workflows/ci.yaml
> +                    - '8.1'
we don't need any version other than php 8.2 and symfony 6.3

2023-11-16 15:33 UTC, JarJak commented on composer.json
> +        "php": ">=8.1",
8.2

2023-11-16 15:33 UTC, JarJak commented on rector.php
> +            SymfonyLevelSetList::UP_TO_SYMFONY_63,
can we upgrade php as well?

2023-11-16 15:33 UTC, JarJak commented on src/Context/MessengerContext.php
> +        $actualMessageCount = count(new Collection($this->getEnvelopesFromTransport($transportName)));
why this needs to be collected before count?

2024-01-03 15:23 UTC, closed without merging